repos:
  - repo: 'https://github.com/mgedmin/check-manifest'
    rev: '0.46'
    hooks:
      - id: check-manifest
  - repo: 'https://github.com/pre-commit/mirrors-prettier'
    rev: ''
    hooks:
      - id: prettier
  - repo: 'https://github.com/pre-commit/mirrors-eslint'
    rev: ''
    hooks:
      - id: eslint
