[build-system]
requires = ["jupyter_packaging~=0.9.1"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"

# setup.cfg or tox.ini
[tool.check-manifest]
ignore = [
    ".binder/**",
    "jupyterlab_markup/labextension/**",
    ".eslint*",
    ".pre-commit-config.yaml",
    ".prettier*",
    "CONTRIBUTING.md",
    "yarn.lock"
]